image:
  name: sonarsource/sonar-scanner-cli:latest
  entrypoint: [""]
variables:
  SONAR_TOKEN: $SONAR_LOGIN
  SONAR_HOST_URL: $SONAR_URL
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  script:
    - sonar-scanner
  allow_failure: false

only:
  - master