name: Build Android adhoc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android-adhoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore: ${{ secrets.SIGNING_KEY }}
          keystore_password: ${{ secrets.STORE_PASSWORD }}
          key_alias: release
          key_password: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  upload-android:
    needs: build-android-adhoc
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: devs
          file: /app/build/outputs/bundle/release/app-release.apk

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build-android-adhoc
      - upload-android
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: https://discord.com/api/webhooks/869272552755830814/Cx1tbPb0L3Ecg1WCv4XRsXr11lN-dBG78INmrIO9qMLbz6l8s8bNAUVg79UJJPcMdBnO

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: https://discord.com/api/webhooks/869272552755830814/Cx1tbPb0L3Ecg1WCv4XRsXr11lN-dBG78INmrIO9qMLbz6l8s8bNAUVg79UJJPcMdBnO

      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: https://discord.com/api/webhooks/869272552755830814/Cx1tbPb0L3Ecg1WCv4XRsXr11lN-dBG78INmrIO9qMLbz6l8s8bNAUVg79UJJPcMdBnO
