name: Build Android adhoc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android-adhoc:
    runs-on: ubuntu-latest
    steps:
      - name: React Native Build
        uses: bamachoub/react-native-build-action@v1.0.0

  upload-android:
    needs: build-android-adhoc
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: devs
          file: app/build/outputs/apk/release/app-release.apk
